# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/fumeron/Programmation C/Retarded_Peace"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/fumeron/Programmation C/Retarded_Peace"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/fumeron/Programmation C/Retarded_Peace/CMakeFiles" "/home/fumeron/Programmation C/Retarded_Peace/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/fumeron/Programmation C/Retarded_Peace/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SOURCES

# Build rule for target.
SOURCES: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SOURCES
.PHONY : SOURCES

# fast build rule for target.
SOURCES/fast:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/build
.PHONY : SOURCES/fast

#=============================================================================
# Target rules for targets named test_colorPalier0

# Build rule for target.
test_colorPalier0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_colorPalier0
.PHONY : test_colorPalier0

# fast build rule for target.
test_colorPalier0/fast:
	$(MAKE) -f CMakeFiles/test_colorPalier0.dir/build.make CMakeFiles/test_colorPalier0.dir/build
.PHONY : test_colorPalier0/fast

#=============================================================================
# Target rules for targets named test_imagePalier0

# Build rule for target.
test_imagePalier0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_imagePalier0
.PHONY : test_imagePalier0

# fast build rule for target.
test_imagePalier0/fast:
	$(MAKE) -f CMakeFiles/test_imagePalier0.dir/build.make CMakeFiles/test_imagePalier0.dir/build
.PHONY : test_imagePalier0/fast

#=============================================================================
# Target rules for targets named test_opencv

# Build rule for target.
test_opencv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_opencv
.PHONY : test_opencv

# fast build rule for target.
test_opencv/fast:
	$(MAKE) -f CMakeFiles/test_opencv.dir/build.make CMakeFiles/test_opencv.dir/build
.PHONY : test_opencv/fast

#=============================================================================
# Target rules for targets named test_vectorimagePalier0

# Build rule for target.
test_vectorimagePalier0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_vectorimagePalier0
.PHONY : test_vectorimagePalier0

# fast build rule for target.
test_vectorimagePalier0/fast:
	$(MAKE) -f CMakeFiles/test_vectorimagePalier0.dir/build.make CMakeFiles/test_vectorimagePalier0.dir/build
.PHONY : test_vectorimagePalier0/fast

src/color.o: src/color.cpp.o
.PHONY : src/color.o

# target to build an object file
src/color.cpp.o:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/color.cpp.o
.PHONY : src/color.cpp.o

src/color.i: src/color.cpp.i
.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s
.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/image.o: src/image.cpp.o
.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i
.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s
.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/palier0/testColor.o: src/palier0/testColor.cpp.o
.PHONY : src/palier0/testColor.o

# target to build an object file
src/palier0/testColor.cpp.o:
	$(MAKE) -f CMakeFiles/test_colorPalier0.dir/build.make CMakeFiles/test_colorPalier0.dir/src/palier0/testColor.cpp.o
.PHONY : src/palier0/testColor.cpp.o

src/palier0/testColor.i: src/palier0/testColor.cpp.i
.PHONY : src/palier0/testColor.i

# target to preprocess a source file
src/palier0/testColor.cpp.i:
	$(MAKE) -f CMakeFiles/test_colorPalier0.dir/build.make CMakeFiles/test_colorPalier0.dir/src/palier0/testColor.cpp.i
.PHONY : src/palier0/testColor.cpp.i

src/palier0/testColor.s: src/palier0/testColor.cpp.s
.PHONY : src/palier0/testColor.s

# target to generate assembly for a file
src/palier0/testColor.cpp.s:
	$(MAKE) -f CMakeFiles/test_colorPalier0.dir/build.make CMakeFiles/test_colorPalier0.dir/src/palier0/testColor.cpp.s
.PHONY : src/palier0/testColor.cpp.s

src/palier0/testImage.o: src/palier0/testImage.cpp.o
.PHONY : src/palier0/testImage.o

# target to build an object file
src/palier0/testImage.cpp.o:
	$(MAKE) -f CMakeFiles/test_imagePalier0.dir/build.make CMakeFiles/test_imagePalier0.dir/src/palier0/testImage.cpp.o
.PHONY : src/palier0/testImage.cpp.o

src/palier0/testImage.i: src/palier0/testImage.cpp.i
.PHONY : src/palier0/testImage.i

# target to preprocess a source file
src/palier0/testImage.cpp.i:
	$(MAKE) -f CMakeFiles/test_imagePalier0.dir/build.make CMakeFiles/test_imagePalier0.dir/src/palier0/testImage.cpp.i
.PHONY : src/palier0/testImage.cpp.i

src/palier0/testImage.s: src/palier0/testImage.cpp.s
.PHONY : src/palier0/testImage.s

# target to generate assembly for a file
src/palier0/testImage.cpp.s:
	$(MAKE) -f CMakeFiles/test_imagePalier0.dir/build.make CMakeFiles/test_imagePalier0.dir/src/palier0/testImage.cpp.s
.PHONY : src/palier0/testImage.cpp.s

src/palier0/testVectorimage.o: src/palier0/testVectorimage.cpp.o
.PHONY : src/palier0/testVectorimage.o

# target to build an object file
src/palier0/testVectorimage.cpp.o:
	$(MAKE) -f CMakeFiles/test_vectorimagePalier0.dir/build.make CMakeFiles/test_vectorimagePalier0.dir/src/palier0/testVectorimage.cpp.o
.PHONY : src/palier0/testVectorimage.cpp.o

src/palier0/testVectorimage.i: src/palier0/testVectorimage.cpp.i
.PHONY : src/palier0/testVectorimage.i

# target to preprocess a source file
src/palier0/testVectorimage.cpp.i:
	$(MAKE) -f CMakeFiles/test_vectorimagePalier0.dir/build.make CMakeFiles/test_vectorimagePalier0.dir/src/palier0/testVectorimage.cpp.i
.PHONY : src/palier0/testVectorimage.cpp.i

src/palier0/testVectorimage.s: src/palier0/testVectorimage.cpp.s
.PHONY : src/palier0/testVectorimage.s

# target to generate assembly for a file
src/palier0/testVectorimage.cpp.s:
	$(MAKE) -f CMakeFiles/test_vectorimagePalier0.dir/build.make CMakeFiles/test_vectorimagePalier0.dir/src/palier0/testVectorimage.cpp.s
.PHONY : src/palier0/testVectorimage.cpp.s

src/test_opencv/main.o: src/test_opencv/main.cpp.o
.PHONY : src/test_opencv/main.o

# target to build an object file
src/test_opencv/main.cpp.o:
	$(MAKE) -f CMakeFiles/test_opencv.dir/build.make CMakeFiles/test_opencv.dir/src/test_opencv/main.cpp.o
.PHONY : src/test_opencv/main.cpp.o

src/test_opencv/main.i: src/test_opencv/main.cpp.i
.PHONY : src/test_opencv/main.i

# target to preprocess a source file
src/test_opencv/main.cpp.i:
	$(MAKE) -f CMakeFiles/test_opencv.dir/build.make CMakeFiles/test_opencv.dir/src/test_opencv/main.cpp.i
.PHONY : src/test_opencv/main.cpp.i

src/test_opencv/main.s: src/test_opencv/main.cpp.s
.PHONY : src/test_opencv/main.s

# target to generate assembly for a file
src/test_opencv/main.cpp.s:
	$(MAKE) -f CMakeFiles/test_opencv.dir/build.make CMakeFiles/test_opencv.dir/src/test_opencv/main.cpp.s
.PHONY : src/test_opencv/main.cpp.s

src/tile.o: src/tile.cpp.o
.PHONY : src/tile.o

# target to build an object file
src/tile.cpp.o:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/tile.cpp.o
.PHONY : src/tile.cpp.o

src/tile.i: src/tile.cpp.i
.PHONY : src/tile.i

# target to preprocess a source file
src/tile.cpp.i:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/tile.cpp.i
.PHONY : src/tile.cpp.i

src/tile.s: src/tile.cpp.s
.PHONY : src/tile.s

# target to generate assembly for a file
src/tile.cpp.s:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/tile.cpp.s
.PHONY : src/tile.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/SOURCES.dir/build.make CMakeFiles/SOURCES.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SOURCES"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_colorPalier0"
	@echo "... test_imagePalier0"
	@echo "... test_opencv"
	@echo "... test_vectorimagePalier0"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/palier0/testColor.o"
	@echo "... src/palier0/testColor.i"
	@echo "... src/palier0/testColor.s"
	@echo "... src/palier0/testImage.o"
	@echo "... src/palier0/testImage.i"
	@echo "... src/palier0/testImage.s"
	@echo "... src/palier0/testVectorimage.o"
	@echo "... src/palier0/testVectorimage.i"
	@echo "... src/palier0/testVectorimage.s"
	@echo "... src/test_opencv/main.o"
	@echo "... src/test_opencv/main.i"
	@echo "... src/test_opencv/main.s"
	@echo "... src/tile.o"
	@echo "... src/tile.i"
	@echo "... src/tile.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

