@startuml


package "static map < string, TypeUnit* > mapTypeUnit" #DDDDDD {
   TypeUnit <-- GenericInfantery
   TypeUnit <-- GenericArtillery
}

note top of TypeUnit : static method <b> getTypeUnit(string _typeName) allow to access to the TypeUnit"


@enduml